{**
 * Phyto Invoice Customizer — PDF invoice footer block.
 * Rendered by hookDisplayPDFInvoiceFooter.
 *
 * Variables:
 *   {$phyto_inv_brand_name}  — escaped brand name
 *   {$phyto_inv_footer_note} — escaped optional footer note (may be empty)
 *}
<table style="width:100%;border-top:1px solid #cccccc;margin-top:10px;font-family:sans-serif;font-size:10px;color:#555555;">
    <tr>
        <td style="padding:6px 0;">

            {* Optional custom footer note *}
            {if $phyto_inv_footer_note}
            <p style="margin:0 0 4px 0;font-style:italic;">
                {$phyto_inv_footer_note|escape:'html':'UTF-8'}
            </p>
            {/if}

            {* Disclaimer *}
            <p style="margin:0 0 2px 0;">
                {l s='All live plant shipments are subject to phytosanitary regulations. Please retain this invoice as proof of legal importation.' mod='phyto_invoice_customizer'}
            </p>

            {* Brand + attribution line *}
            <p style="margin:4px 0 0 0;color:#888888;">
                &copy; {$phyto_inv_brand_name|escape:'html':'UTF-8'}
                &nbsp;&mdash;&nbsp;
                {l s='Generated by PhytoCommerce' mod='phyto_invoice_customizer'}
            </p>

        </td>
    </tr>
</table>
